### PR TITLE
support for ignoring properties and types inheriting from IDictionary<string, object>

### PR DESCRIPTION
**Pull request by gentledepp**
Added support for ignoring properties.

Also primitive support for types implementing IDictionary<string, object> 
which is required for some JSON scenarios (JSON.NET)

Could be improved by implementing a DictionaryInterceptor?

### CODE REVIEW

**Comment by joelweiss** [comment]
Will have a look soon.

**Comment by gentledepp** [comment]
Great!
Please note, however, that this branch is based on pull request #24

**Comment by mattbrailsford** [comment]
Are all these updates still outstanding? Seem to be a lot of useful additions here 🤔

**Comment by joelweiss** [comment]
Thanks for the PR,tThis PR has lots of different changes not only ignoring properties, I thought I might get around to dig in, but that didn't happen...

Closing this PR. feel free to open focused PRs on individual issues.

**Pull request closed without merging**
