### PR TITLE
Skip dynamic object interception

### PR DESCRIPTION
**Pull request by mfidemraizer**
Hey,

I've found an issue when trying to track a class which derived from `System.Dynamic.DynamicObject`. Some calls to its own methods and also interface implementations part of `DynamicObject` produced infinite recursivity when some methods were called, and that was throwing `StackOverflowException` exceptions.

My two cents here have been modifying `ChangeTrackingProxyGenerationHook` to skip intercepting anything related to dynamic objects and the problem I've solved my issue this way. Since dynamic members can be intercepted as part of `DynamicObject.TrySetMember`, I feel that there's no need to inject code there during run-time. In my case, my own dynamic object also implicitly implements `INotifyPropertyChanged`, and it's a mixed concrete and dynamic object. Your library can sucessfully intercept design-time properties and it's enough for now.

Thank you in advance and I'll look forward for your comments.

### CODE REVIEW

**Comment by joelweiss** [comment]
Hi, 
It definitely makes sense to have a way to skip certain types of change tracking, but I'm trying to understand what the use case is, if we are skipping `DynamicObject`s what's the point of tracking it in the first place?

Can you please provide with a failing example, or add failing tests?

**Comment by mfidemraizer** [comment]
Hey,

I'm out of time to implement these tests (I've been daddy just 6 months ago...), but I believe you didn't understand the issue at all.

It might happen that you've implemented a class like `Customer` which also inherits `DynamicObject`, so this means that `Customer` has a compile-time part and a run-time part (the dynamic properties). 

I couldn't find the right reason for the infinite loop because of some recursivity, but it was happening when setting a dynamic property (i.e. `obj.Text` where `Text` is a dynamic property). And it was happening always.

So, at the end of the day, I want to track changes of some class properties but I just want to track non-dynamic ones. Dynamic ones can be tracked implementing `INotifyPropertyChanged` on the `DynamicObject`-derived class and firing the whole event when the runtime calls `TrySetValue`.

**Comment by joelweiss** [comment]
Hi,
To understand the solution, I first have to understand the problem, so if you can please post the code of your implementation of the `DynamicObject`'s overrides because the following works fine.

```charp
[TestMethod]
public void Support_Dynamic()
{
    var order = new DynamicOrder();
    var trackable = order.AsTrackable();
    order.OrderId = 123;

    trackable.Should().BeAssignableTo<IChangeTrackable<DynamicOrder>>();
}

public class DynamicOrder : System.Dynamic.DynamicObject
{
    public override bool TryGetMember(GetMemberBinder binder, out object result)
    {
        return base.TryGetMember(binder, out result);
    }

    public override bool TrySetMember(SetMemberBinder binder, object value)
    {
        return base.TrySetMember(binder, value);
    }

    public virtual int OrderId { get; set; }
}
```

**Comment by nemec** [comment]
@joelweiss I think you need some modifications to lines 2 and 3 of your test example:

```csharp
dynamic trackable = order.AsTrackable();
trackable.OrderId = 123;
```

In my experience, I don't get a StackOverflowException but the code does hang.

**Comment by joelweiss** [comment]
@nemec Thanks, Will check it out as soon as I have a chance.

**Comment by joelweiss** [comment]
I took another look at it, I still don't understand the case for this, if you still face this issue, feel free to reopen with a failing example and use case.

**Pull request closed without merging**
