### PR TITLE
Skip properties with no setters on GetOriginal

### PR DESCRIPTION
**Pull request by solsab**
Fixed issue with "getter only" properties breaking GetOriginal.

### CODE REVIEW

**Comment by joelweiss** [comment]
Thanks, nice catch.

Since this bug affected `AcceptChanges()` and `RejectChanges()` as well, I want to make sure all tests run on a class with a readonly property, so if you can please update your PR and remove the specific `OrderWithCalculatedFields` class and add to `Order.cs`
```csharp
public virtual int OrderDetailsCount => OrderDetails?.Count ?? 0;
```

Thanks

**Comment by solsab** [comment]
Hi Joel,

I added the property the old fashioned way, as I don't yet have C# 6.0 installed.

Thanks,
Solomon

**Comment by joelweiss** [comment]
Thanks.

Still need to delete `OrderWithCalculatedFields.cs`

**Comment by solsab** [comment]
Removed the orphaned file.

**Comment by joelweiss** [comment]
Thanks again

**Pull request merged**
